- presidents/index.html
- presidents/presidents.json
- presidents/presidents.json.backup
In re issue 44:  https://github.com/jermbo/SampleAPIs/issues/44
Adding 'Presidents' folder to SampleAPIs data. Folder includes:
- presidents.json
- presidents.json.backup
- index.html (follows format in other collections)
Feel free to let me know if I'm missing anything!
> Presidents collection

- src/api/css-color-names.json
- src/api/css-color-names.json.backup
- src/apiList.js
- src/views/index.pug
- src/views/page.pug
#62 Adding CSS Color Names Endpoint and improving some documentation.
> 62 css color names

- src/api/beers.json
this was offensively low. Thanks for the cool API :)
> Correct Beer rating

- src/api/the-states.json
- src/apiList.js
Hi there. I would like to submit this api end point that includes info on the 50 states. The data has the state name, abbreviation, capital, largest city, date added to union, population, and the state flag. This is something that I didn't really find out there when I did this [small project.](https://yarocruz.github.io/the50states/). This is not my first pull request, but technically this would be my first attempt a contributing to a project. Hope I did this right. :)
> Adds the-states endpoint

- src/apiList.js
- src/public/assets/styles/code.css
- src/public/assets/styles/home-styles.css
- src/public/scripts/fetchSample.js
- src/sampleapis.js
- src/views/index.pug
- src/views/page.pug
- src/views/partials/header.pug
I found a different way to display the code samples to the users. 
I believe this is a bit more user friendly as it adds syntax highlighting, copy to clipboard function, and is dynamic for each endpoint. 
The `apiList.js`has been cleaned up as the code samples are no longer necessary.
> Code examples

- src/public/scripts/CodeHighlight.js
- src/routes/base-apis.js
- src/sampleapis.js
- src/views/index.pug
- src/views/page.pug
Laying down foundation for future updates by separating the routes into meaningful files.
Renamed the CodeHighlight js file for clarity
Removed unnecessary console.log()'s and white spaces.
> 👌 IMPROVE: Cleanup

- Change_log.md
- README.md
- package.json
Closes #78 
Added updates to documentation and bumped up the current version number.
> 78 Update Docs

- src/api/countries.json
- src/api/countries.json.backup
ADD: media
MOV: flag to media.flag
ADD: media.emblem
ADD: media.orthographic
> Add new data to countries.json

- src/api/rickandmorty.json
- src/api/rickandmorty.json.backup
- src/apiList.js
We are currently missing one of the most important API resources out there in the world. SURE you can get this information by watching all episodes and manually writing that down but why when you can access it now!
> Adding Rick & Morty Data Set because without it we're all lost

- CONTRIBUTING.md
- README.md
Addresses the Issue #https://github.com/jermbo/SampleAPIs/issues/90
I didn't know where else to add it so it's at the bottom.
I wonder if I should also add it to the README.MD ????
🔥 📝
> Add "How to add an Endpoint" to the "CONTRIBUTION.MD" file

- src/apiList.js
Hi, thank you for adding The Rick and Morty API to the list! I love the description and the PR comment in #89 @thedamian  
I'd like to add the website to the description if that's ok
> Update The Rick and Morty API description.

- README.md
- src/apiList.js
I should have giving attribution and even though the great @afuh  inventor of the rickandmortyapi.com repo officially corrected the description I thought my version correctly showed what I did (that I did without permission which was wrong and hopefully brought to light my shame as rick himself would have wanted it.
> Typo on the front screen and giving attribution to RickAndMortyAPI.com

- src/api/futurama.json
I added as many futurama character's images as I could find.
> added images to some futurama characters

- src/public/assets/styles/code.css
- src/views/404.pug
Closes #86 by adding custom styled 404 page.
I'm sorry my linter went a bit crazy on the css file
> ✨ Adds custom 404 page

- src/apiList.js
> 🐛 Fix endpoint Id

- .gitignore
- src/custom/README.md
- src/routes/custom-apis.js
I know the src/custom directory should be ignore (and the .gitignore is update to reflect the contents of this directory.
but not having the directory initially causes the app not to start.
> Adding the src/Custom directory that was missing.

- client/src/components/Nav/Nav.tsx
- client/src/context/GlobalContext.tsx
Updating Environment Variables
> Updating Environment Variables

- server/api/avatar.json
- server/api/avatar.json.backup
Updating Dependancies.
Adding more Characters.
Adding more Questions.
> Avatar data

- server/api/futurama.json
- server/api/futurama.json.backup
Hi Jermbo - I'm in the current Boca Code course, and created a little app with the Futurama character API (thank, btw). It wasn't working when you visited, or I would've shared it then. But I noticed a few image URLs didn't work for me, because they had additional stuff after the file extension. So Todd suggested I do a pull request to 'fix' those (don't know if they were intentional). I also added more images for the remaining characters, and a couple of quotes for Hermes. Let me know if you have any questions. And here's the app, too:
[https://db-futurama-react.web.app/](https://db-futurama-react.web.app/)
Thanks!
Dan
> trimmed some futurama character images, added some, and a couple of Hermes quotes

- client/src/pages/Docs/Docs.tsx
> New changes. New branch
